#!/bin/bash

# Test suite for Airport Scheduling, runs many many tests.

PATH="/home/user001/dev/gen/project/AirportScheduling"

FITNESSFUNCTION="FUEL TIME"
SELECTORFUNCTION="FITTEST TOURNAMENT ROULETTE"
MUTATORFUNCTION="SIMPLE SUBTRACT ADD COMBO"
COMBINATORFUNCTION="SIMPLE RANDOM AVERAGE BLOCK TIME"

PLANESIZES="10 50 100 200 500 1000"
POPULATIONSIZE=250
#PLANESIZES="10"
#POPULATIONSIZES="25"

#echo "Starting Fitness Function test" >> testresult
#for ((i=0;i<3;i+=1));
#do
#    echo "Fitness testrun: '$i'" >> testresult
#    for a in $FITNESSFUNCTION
#    do
#        for e in $PLANESIZES
#        do
#            output=`$PATH/bin/AirportScheduler -csv --no-results -G 100 -P $POPULATIONSIZE -p $e -F $a huge_testfile`
#            echo $output
#            echo $output >> testresult
#        done
#    done
#done
#
#echo "Starting Selector Function test" >> testresult
#
for ((i=0;i<3;i+=1));
do
    echo "Selector testrun: '$i'" >> testresult
    for b in $SELECTORFUNCTION
    do
        for e in $PLANESIZES
        do
            output=`$PATH/bin/AirportScheduler -csv --no-results -G 100 -P $POPULATIONSIZE -p $e -S $b huge_testfile`
            echo $output
            echo $output >> testresult
        done
    done
done
#
#echo "Starting mutator Function test" >> testresult
#for ((i=0;i<3;i+=1));
#do
#    echo "Selector testrun: '$i'" >> testresult
#    for c in $MUTATORFUNCTION
#    do
#        for e in $PLANESIZES
#        do
#            output=`$PATH/bin/AirportScheduler -csv --no-results -G 100 -P $POPULATIONSIZE -p $e -M $c huge_testfile`
#            echo $output
#            echo $output >> testresult
#        done
#    done
#done
#
#echo "Starting combinator Function test" >> testresult
#for ((i=0;i<3;i+=1));
#do
#    echo "Selector testrun: '$i'" >> testresult
#    for d in $COMBINATORFUNCTION
#    do
#        for e in $PLANESIZES
#        do
#            output=`$PATH/bin/AirportScheduler -csv --no-results -G 100 -P $POPULATIONSIZE -p $e -C $d huge_testfile`
#            echo $output
#            echo $output >> testresult
#        done
#    done
#done
#
#echo "Test Suite is finished"
#
exit 0
